FROM keepwondering/pleasure-cli
ENV PLEASURE_MODE=3-tier
ENV PLEASURE_CLIENT_APP_URL={{{ appURL }}}
ENV PLEASURE_CLIENT_APP_SERVER_URL=http://api
ENV PLEASURE_API_MONGODB_HOST=mongo
ENV NODE_ENV=production
WORKDIR /app
COPY . /app
RUN yarn --production=false
RUN yarn pls app gencert --jwt
RUN yarn build
EXPOSE 3000
CMD pls app dev --api
