FROM keepwondering/pleasure-cli:nginx
ENV PLEASURE_MODE=3-tier
ENV PLEASURE_CLIENT_APP_URL={{{ appURL }}}
ENV PLEASURE_CLIENT_APP_SERVER_URL=http://api
ENV NGINX_CONFIG=/nginx-config.conf
ENV NODE_ENV=production
WORKDIR /app
COPY . /app
RUN yarn --production=false
RUN pls app build
RUN pls app deploy nginx --apiHost api --nginxDestination $NGINX_CONFIG
EXPOSE 80
CMD nginx -c $NGINX_CONFIG && pls app dev --ui
